### ISSUE TITLE
`ghcr.io/hashgraph/hedera-json-rpc-relay:0.2.0` image becomes "unhealthy" a few mins after running docker file

### ISSUE THREAD

**Issue by mgarbs** [hashgraph/hedera-local-node#107]
### Description

NOTE: Using macOS w/ M1 chipset

What happens:
hashgraph/hedera-json-rpc-relay image goes into and unhealthy state after running the docker file and waiting a few mins

Expected behavior:
hashgraph/hedera-json-rpc-relay image to spin up into healthy state with no issues

### Steps to reproduce

1. run `docker compose up -d` in root folder
2. wait a few mins
3. check the containers `docker ps`

### Additional context

```bash
➜  hedera-local-node git:(main) ✗ docker ps           
CONTAINER ID   IMAGE                                                COMMAND                  CREATED          STATUS                             PORTS                                             NAMES
f64e46624365   ghcr.io/hashgraph/hedera-json-rpc-relay:0.2.0        "npm run start"          41 seconds ago   Up 38 seconds (health: starting)   0.0.0.0:7546->7546/tcp                            json-rpc-relay


wait a few mins then run the same command...


➜  hedera-local-node git:(main) ✗ docker ps
CONTAINER ID   IMAGE                                                COMMAND                  CREATED              STATUS                          PORTS                                             NAMES
f64e46624365   ghcr.io/hashgraph/hedera-json-rpc-relay:0.2.0        "npm run start"          About a minute ago   Up About a minute (unhealthy)   0.0.0.0:7546->7546/tcp                            json-rpc-relay
 
```

### Hedera network

other

### Version

v1.0.3

### Operating system

macOS

**Comment by nathanklick** [comment]
@mgarbs Thanks for reporting this issue. We have confirmed the problem. We have a fix in progress and will update you shortly.

**Comment by Nana-EC** [comment]
`0.3.0` image now available and should addres this.
Workaround is to set the `RELAY_IMAGE_TAG` environment variable to `0.3.0`

Updating PR to come soon

**Comment by Kalina-Todorova** [comment]
Hi, we have updated the relay image to `0.3.0`
Can you confirm that all is working properly now?
