### ISSUE TITLE
No consensus confirmation and missing libraries for json-rpc-relay

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-local-node#114]
### Description

A user provided the feedback for improvement regarding doc examples, Hedera local node, and hethers+hardhat. The points below focus on local node:

```
Using ethers +hardhat + eth I can compile and deploy my libraries, then my main contracts, load my facets , beat them up and recycle as many times and (almost) as fast as I like
Using hethers + hardhat +local Hedera node, I can compile my libraries, and deploy them if I just ignore the wait for a confirmation and take it on trust.
This is the issue I raised about consensus never coming back, now I ignore it I have moved on to the next issue.
Normally the inclusion of libraries would pretty much take care of itself in the hardhat compile, with a libraries array being passed in when needed.
I have had so much issue with the hethers + hardhat that I have reverted to calculating the $hex$ code and doing a substitution on the bytecode before attempting to deploy it.
 ...
All of this is on top of a local hedera system that almost works, i.e. there are still missing libraries in the latest docker pull for the  json-rpc-relay ( requires lerna ) which I results in the container coming up unhealthy (i.e. not running) , which may be why it does not reach consensus, I was actually beyond caring when I noticed that the json-rpc-relay had reverted with the latest pull, I had previously fixed it locally and notified abi, but was back developing on a working eth system to get some work done.

If you have a working local system you take pressure off of the test system, which I know has been having its own issues recently. 
It also allows developers to beat the #### out of their ideas and setups prior to doing that on the test system.
The local system appears to have come along as an afterthought, it needs to be front and centre as an adoption multiplier tool, along with example code that goes beyond the toddler steps and deals with some real world deployment scenarios. Maybe this all exists, but not where I have found it.  If you want people to follow the path, you have to smooth the road.
```

### Steps to reproduce

**From feedback above:**

1. Using hethers + hardhat +local Hedera node, I can compile my libraries, and deploy them if I just ignore the wait for a confirmation and take it on trust.
This is the issue I raised about consensus never coming back, now I ignore it I have moved on to the next issue.

2. there are still missing libraries in the latest docker pull for the  json-rpc-relay ( requires lerna ) which I results in the container coming up unhealthy (i.e. not running) , which may be why it does not reach consensus...

### Hedera network

other

### Version

v1.0.3

### Operating system

Windows

**Comment by nathanklick** [comment]
Issue #107 is related to this ticket.

**Comment by nathanklick** [comment]
@ed-marquez Would it possible to ask the user to provide the system information requested below? 

- Operating System Version 
   - On Windows: `systeminfo` from the Windows Command Prompt
   - On Linux: `cat /etc/os-release /etc/redhat-release /etc/centos-release` from the command shell
   - On MacOS X: `system_profiler SPSoftwareDataType` from the command shell 
- Docker Version Info
   - On All Operating Systems: `docker version` from the command shell/prompt

**Comment by nathanklick** [comment]
@ed-marquez Also please ask him for the commit SHA hash which he is testing against, if possible.

**Comment by Nana-EC** [comment]
`0.3.0` image is available.
Updating PR to be added soon

**Comment by Kalina-Todorova** [comment]
Hi, we have updated the relay image to `0.3.0`
Can you confirm that all is working properly now?
