### ISSUE TITLE
hedera-local-node don't work on Windows using WSL [users haven't been created]

### ISSUE THREAD

**Issue by nikania** [hashgraph/hedera-local-node#132]
### Discussed in https://github.com/hashgraph/hedera-local-node/discussions/127

<div type='discussions-op-text'>

<sup>Originally posted by **nikania** July 22, 2022</sup>
I don't know if it's a bug or if I'm doing something incorrectly.

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19044 N/A Build 19044
Docker version 20.10.14, build a224086
docker-compose version 1.29.2, build 5becea4c

Problem:
` docker-compose up -d` starts and runs all services, but logs on database `mirror-node-db` say that no user roles have been created:

```
UTC [295] FATAL:  password authentication failed for user "mirror_api"
UTC [295] DETAIL:  Role "mirror_api" does not exist.
Connection matched pg_hba.conf line 99: "host all all all scram-sha-256"
UTC [296] FATAL:  password authentication failed for user "mirror_node"
UTC [296] DETAIL:  Role "mirror_node" does not exist.
Connection matched pg_hba.conf line 99: "host all all all scram-sha-256"
```

Therefore, the node isn't working. Any suggestions? [ I tried changing line-ending in *.sh scripts to LF - didn't work, tried to run `docker-compose` as administrator - also didn't work ]</div>

**Comment by Ivo-Yankov** [comment]
Are you starting the local node through the npx command `npx hedera-local start`? Could you also please provide the full output log.

**Comment by Kalina-Todorova** [comment]
Hi @nikania could you confirm that the issue is resolved with Release v.1.2.0?

**Comment by nikania** [comment]
@Kalina-Todorova yes, hedera-local-node is working
