### ISSUE TITLE
Dev branch with latest network and mirror node images

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-local-node#146]
### Problem

In the [.env](https://github.com/hashgraph/hedera-local-node/blob/main/.env) file we have the latest version of the images on mainnet.

### Solution

Create a develop branch where we have the newest images (alpha, pre-release) to be able to run against them.

**Comment by georgi-l95** [comment]
Closing this issue, dev branch created with latest versions for network node, mirror node and relay.
