### ISSUE TITLE
Hedera node does not start

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [hashgraph/hedera-local-node#154]
Executing the following steps:
1. `npm install @hashgraph/hedera-local -g`
2. `hedera start`
yields the following error on the container for the consensus node
![Screenshot 2022-08-27 at 16 49 31](https://user-images.githubusercontent.com/12232750/187033183-a140d0e6-11c8-4749-bdce-40237761e5d7.png)

**Comment by Kalina-Todorova** [comment]
Cannot reproduce.
