### ISSUE TITLE
Update consensus node CHAIN_ID to 298

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-local-node#156]
### Description

As noted in the https://github.com/hashgraph/hedera-json-rpc-relay/ README:
`The network chain id. Local and previewnet envs should use 0x12a (298). Previewnet, Testnet and Mainnet should use 0x129 (297), 0x128 (296) and 0x127 (295) respectively`
Let's update the CHAIN_ID to be the correct one for local environment. 

### Steps to reproduce

When running the local node.

### Hedera network

other

### Version

v1.2.0

**Comment by mshakeg** [comment]
@Kalina-Todorova is this issue related to [this issue](https://github.com/hashgraph/hedera-json-rpc-relay/issues/488) I came across in the example projects.

**Comment by georgi-l95** [comment]
Probably yes, local node was configured to work with `testnet - 0x128 (296) ` , while relay is configured to work with `0x12a (298)` .This should be fixed now.

**Comment by georgi-l95** [comment]
Not sure about next release, but you can start the relay locally and after that start the hedera-local (this way the relay container won't start). Just make sure their chain id are the same. Either testnet or local. Checkout how to start it in the relay repo.
