### ISSUE TITLE
Local Node should accept TX > 6kb

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [hashgraph/hedera-local-node#159]
At the moment there is a big slow down due to File Create / Appends (6KB limits) when developers are deploying contracts in their tests.

Ideally the local environment must be as fast as possible -> having deployment of a contract span several seconds is too slow. 

Proposed solution:
- Add an option to change the max TX bytes to >25kb when running the local node

**Comment by mshakeg** [comment]
@Daniel-K-Ivanov the issue isn't limited to contract deployments taking several seconds, but pretty much everything taking way longer than it should on a local dev environment. The node start time including the creation of the account sets takes about 1 minute compared to ~1s for other local blockchains like ganache and hardhat.
