### ISSUE TITLE
Speed up hedera local node start time

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-local-node#162]
### Problem

The hedera local node start time currently takes about a 90s which is significantly longer than the start time of other local nodes such as ganache and hardhat which take about 1s.

About 60s is the time to start all docker containers and another 30s to create the initial account sets.

### Solution

1. Speed up the accounts set creation process by running the `HederaUtils` methods `generateECDSA`, `generateAliasECDSA` and `generateED25519` asynchronously, in addition, run all account creations asynchronously within each of those generate functions.
2. Investigate optimisation for decreasing time to start all docker containers

**Comment by mshakeg** [comment]
With the changes introduced in #243 the local node start up time is faster, however the `network-node` container still takes significantly longer than other containers to start up(~32.7s as shown below):
```
[+] Running 22/22
 ⠿ Network mirror-node                  Created                                                                 0.0s
 ⠿ Network network-node-bridge          Created                                                                 0.0s
 ⠿ Network json-rpc-relay               Created                                                                 0.0s
 ⠿ Network hedera-local-node_default    Created                                                                 0.0s
 ⠿ Network cloud-storage                Created                                                                 0.0s
 ⠿ Volume "minio-data"                  Created                                                                 0.0s
 ⠿ Volume "mirror-node-postgres"        Created                                                                 0.0s
 ⠿ Container hedera-explorer            Started                                                                 1.1s
 ⠿ Container mirror-node-db             Started                                                                 1.3s
 ⠿ Container envoy-proxy                Started                                                                 1.2s
 ⠿ Container minio                      Started                                                                 1.2s
 ⠿ Container haveged                    Started                                                                 1.0s
 ⠿ Container account-balances-uploader  Started                                                                 1.7s
 ⠿ Container record-streams-uploader    Started                                                                 1.6s
 ⠿ Container record-sidecar-uploader    Started                                                                 1.7s
 ⠿ Container mirror-node-importer       Started                                                                 1.7s
 ⠿ Container network-node               Healthy                                                                32.7s
 ⠿ Container mirror-node-web3           Started                                                                 2.2s
 ⠿ Container mirror-node-rest           Started                                                                 2.1s
 ⠿ Container mirror-node-grpc           Started                                                                 2.9s
 ⠿ Container json-rpc-relay             Started                                                                 3.0s
 ⠿ Container mirror-node-monitor        Started                                                                32.8s
 ```

**Comment by Nana-EC** [comment]
@georgi-l95 I think the numbers are better here. Let's update this as I believe the remaining time is mostly around account creation and not the network node spin up right?

**Comment by Nana-EC** [comment]
> Speed up the accounts set creation process by running the HederaUtils methods generateECDSA, generateAliasECDSA and generateED25519 asynchronously, in addition, run all account creations asynchronously within each of those generate functions.

@mshakeg we're looking into this. Currently a sequential account creation provides reliability between key and accountID value mapping. However, we could adopt a similar flow to previewnet and testnet resets in which the key is assured but your accountId could change between instances of the network, this would be the result of asynchronous running.
Would this be something that would break you and other developers?

**Comment by mshakeg** [comment]
@Nana-EC my usage does not require reliable mapping of a key to an accountId, but according to @stoqnkpL some [developers may require this](https://github.com/hashgraph/hedera-local-node/pull/165#issuecomment-1259344358).

From my testing, as pointed out in the above PR's description the network node startup time is primarily due to the synchronous accounts creation, and running the accounts creation asynchronously only takes a ~1s.

**Comment by georgi-l95** [comment]
> @georgi-l95 I think the numbers are better here. Let's update this as I believe the remaining time is mostly around account creation and not the network node spin up right?

Yes, the rest of the time is taken for account creation.
