### ISSUE TITLE
Write a Helm chart for local-node

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-local-node#189]
### Problem

We should run on a cloud managed Kubernetes (GKE, EKE, AKS) that ops creates and manages.

### Solution

- Write a [Helm](https://helm.sh/) chart for local node and manage the deployments.

**Comment by Kalina-Todorova** [comment]
Depends on: https://github.com/hashgraph/hedera-services/issues/4068

**Comment by Kalina-Todorova** [comment]
Depends on: https://github.com/hashgraph/hedera-mirror-node-explorer/issues/282

**Comment by yaroslav-007** [comment]
Hello,

We have implemented options for running local node in cloud environment:
 - Codespace: https://github.com/hashgraph/hedera-local-node/blob/main/docs/codespacs-setup.md
 - Gitpod: https://github.com/hashgraph/hedera-local-node/blob/main/docs/gitpod-setup.md
