### ISSUE TITLE
npm install --save -dev 'hedera-local' gives following error, pls help

### ISSUE THREAD

**Issue by jigsnptel** [hashgraph/hedera-local-node#23]
npm install --save-dev 'hedera-local'
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/'hedera-local' - Not found
npm ERR! 404
npm ERR! 404  ''hedera-local'@*' is not in this registry.
npm ERR! 404 This package name is not valid, because
npm ERR! 404  1. name can no longer contain special characters ("~'!()*")
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Vipul\AppData\Local\npm-cache\_logs\2022-04-24T14_14_39_786Z-debug-0.log

**Comment by jigsnptel** [comment]
node version 16.14.2
npm version 8.7.0
Docker version 20.10.13, build a224086

**Comment by jigsnptel** [comment]
i request you to pls urgently help with the issues, as my research work is pending because of this.

**Comment by natanasow** [comment]
The package had been moved under the @hashgraph organization, and the right way to install it now is via "npm install --save-dev '@hashgraph/hedera-local'"
