### ISSUE TITLE
local-node genesis block is 1 instead of 0 

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-local-node#230]
**Problem:** Mainnet has 0 block since mirrornode on mainnet set genesis block number to 0 and when v6 record file was introduced and block number enabled, services was configured to sync with mirrornode to increase the block number. Other networks including testnet had reset and started with v6 record file.

**Comment by Nana-EC** [comment]
Should be addressed by https://github.com/hashgraph/hedera-services/pull/7193

**Comment by georgi-l95** [comment]
This is fixed with 0.40-alpha.0. Closing this.
