### ISSUE TITLE
Cannot access local hashscan explorer

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-local-node#232]
### Description

I cannot access the hashscan explorer which I previously was able to(on earlier local node versions) at http://localhost:9090/ however on the latest release(2.2.1)

### Steps to reproduce

1. Install `@hashgraph/hedera-local@2.2.1`
2. Start up local node: `npx @hashgraph/hedera-local start`
3. Observe that the `hedera-mirror-node-explorer` container is running in docker however cannot be accessed at http://localhost:9090/

### Hedera network

other

### Version

@hashgraph/hedera-local@2.2.1

### Operating system

macOS

**Comment by nathanklick** [comment]
@Kalina-Todorova It loooks like the documentation is out of date amd the nginx port is incorrectly set in the `docker-compose.yaml` file.

https://github.com/hashgraph/hedera-local-node/blob/28786deef98c5b644dd0acbb0c161c579295ea70/docker-compose.yml#L280

The official Mirror Node Explorer container uses port 8080 for nginx.
https://github.com/hashgraph/hedera-mirror-node-explorer/blob/ddaac2280b0450d526bcb6f61307b263e6f1f834/docker-compose.yml#L8

**Comment by Kalina-Todorova** [comment]
@nathanklick @mshakeg will update the documentation

**Comment by georgi-l95** [comment]
This is fixed, another issue is present. Will be addressed [here](https://github.com/hashgraph/hedera-local-node/issues/240)
