### ISSUE TITLE
dev mode does not fix hardhat chai matcher revert issue

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-local-node#233]
### Description

dev mode was initially introduced to resolve [this issue](https://github.com/hashgraph/hedera-json-rpc-relay/issues/661) however this is still an issue on the local-node's latest release.

### Steps to reproduce

1. Install local-node@latest `npm i @hashgraph/hedera-local@2.2.1`
2. Start up the local node with dev mode: `npx @hashgraph/hedera-local start --limits=false --dev=true`
3. Run the test script(`npm run test:hec`) in [this pr](https://github.com/hashgraph/hedera-json-rpc-relay/pull/660)
4. Observe that the tests fail

### Hedera network

other

### Version

@hashgraph/hedera-local@2.2.1

### Operating system

macOS

**Comment by Kalina-Todorova** [comment]
Hi @mshakeg we will look into this.

**Comment by natanasow** [comment]
@mshakeg the fix is included in [hedera-local@2.3.0](https://www.npmjs.com/package/@hashgraph/hedera-local/v/2.3.0)

**Comment by mshakeg** [comment]
@natanasow great to hear, will test it out asap, is there a reason the mirror node image wasn't updated? mirror-node@0.69.0 has a create2 address fix I'd like to test, in addition apparently [0.69.1](https://github.com/hashgraph/hedera-mirror-node/releases/tag/v0.69.1) has a high severity fix.

Also, could the node&haveged images be updated to the following, I'd like to test if it fixes [this issue](https://github.com/hashgraph/hedera-json-rpc-relay/issues/645). I'd prefer not to setup my own local-node config as I have the local-node as a dev dependency in my project.
```
"nodeImageTag": "0.32.0",
"havegedImageTag": "0.32.0", 
```
They're currently on the following version:
```
  "nodeImageTag": "0.32.0-alpha.1",
  "havegedImageTag": "0.32.0-alpha.1",
```

**Comment by mshakeg** [comment]
@natanasow updating the relay image fixing this issue, however, [this issue](https://github.com/hashgraph/hedera-json-rpc-relay/issues/645) is still frustrating.

**Comment by natanasow** [comment]
@mshakeg we just released a patched version with the latest mirror node version [hedera-local@2.3.1](https://www.npmjs.com/package/@hashgraph/hedera-local/v/2.3.1)

**Comment by mshakeg** [comment]
@natanasow thanks, the local-node is smoother though still has an `HBAR Rate limit exceeded` issue. Will create a separate issue for that.

**Comment by georgi-l95** [comment]
@mshakeg This is working on your side now, right ?

**Comment by mshakeg** [comment]
@georgi-l95 yes the original issue.

**Comment by georgi-l95** [comment]
This issue is fixed. Closing this ticket.
