### ISSUE TITLE
Update "address" to "public address"

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-local-node#280]
### Problem

The CLI tool creates ECDSA accounts on start up. The second table that is displayed in the console in the second column reads "address." Hedera accounts have many addresses in the system like account IDs, public key aliases, etc. The column name should be updated to state "public address" to specify the exact address type. 
![Screenshot 2023-02-16 at 8 37 04 PM](https://user-images.githubusercontent.com/21989138/219550574-3e6a03ed-e07b-46f1-832e-3af10911cf78.png)

### Solution

Update the column name from "address" to "public address."

**Comment by georgi-l95** [comment]
Addressed in #284
