### ISSUE TITLE
Add EVM optimized run mode docs

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-local-node#287]
### Problem

Network execution  E2E remains under 10s and on local node is sometimes around ~5-7 seconds.
However, for devs used to local EVM tooling solutions (e.g. hardhat, ganache etc) this is 5X-7X slower than what they'd expect.

Advancements were taken to allow the local node to be configured to optimize excution for EVM scenarios.
However, no documentation exists to make clear what the changes are that support the item and what commands/setup is necessary to achieve this optimized mode

### Solution

Add `docs/evm-optimized.md` which offers and overview of 
- [ ] List of changes made to support change
- [ ] console commands and setup to run env
- [ ] architecture diagrams to illustrate where the system differs from a regular mode run

**Comment by mshakeg** [comment]
@Nana-EC the 5-7x slower estimate is quite generous imo. The hedera local node is much slower at deploying larger contracts(i.e. close to the max contract size of ~24KB, and also does not `allowUnlimitedContractSize` as hardhat does) and is overall much slower even at contact transactions and calls(i.e.`eth_call`).

For example, the following simple test script that deploys very small contracts(<4KB and so does not require FileAppendTransactions).

Performance on the hedera local node:
```
    ✔ iteration: 0; should be able to delete contract via Deletable#destroy() (5483ms)
    ✔ iteration: 0; should be able to delete deletable2 and re-create it (12409ms)
    ✔ iteration: 1; should be able to delete contract via Deletable#destroy() (4722ms)
    ✔ iteration: 1; should be able to delete deletable2 and re-create it (11476ms)
```

Performance on the hardhat local node:
```
    ✔ iteration: 0; should be able to delete contract via Deletable#destroy() (844ms)
    ✔ iteration: 0; should be able to delete deletable2 and re-create it (91ms)
    ✔ iteration: 1; should be able to delete contract via Deletable#destroy() (42ms)
    ✔ iteration: 1; should be able to delete deletable2 and re-create it (72ms)
```

As you can see on hardhat only the very first test case takes considerably longer than the other test cases and is 6.49x faster than the hedera local node, but in all of the subsequent test cases hardhat is anywhere from 112x to 160x faster. In the case of large contract deploys hardhat could be close to 3 orders of magnitude faster than the hedera local node.

**Comment by georgi-l95** [comment]
Hey @mshakeg can you give us some of those contracts that you’re benchmarking, to try and do some speedtests and improvements, if possible ?

**Comment by mshakeg** [comment]
Hey @georgi-l95 sure, all of the contracts are in [my fork on the hedera-json-rpc-relay](https://github.com/mshakeg/hedera-json-rpc-relay).

My previous comment compares the performance on the `./test/deletable.test.ts` script.

**Comment by georgi-l95** [comment]
> Hey @georgi-l95 sure, all of the contracts are in the `hardhat-example` project [of my fork on the hedera-json-rpc-relay](https://github.com/mshakeg/hedera-json-rpc-relay).
> 
> My previous comment compares the performance on the `./test/deletable.test.ts` script.

Thank you.

**Comment by Nana-EC** [comment]
> 



> @Nana-EC the 5-7x slower estimate is quite generous imo. The hedera local node is much slower at deploying larger contracts(i.e. close to the max contract size of ~24KB, and also does not `allowUnlimitedContractSize` as hardhat does) and is overall much slower even at contact transactions and calls(i.e.`eth_call`).
> 
> For example, the following simple test script that deploys very small contracts(<4KB and so does not require FileAppendTransactions).
> 
> Performance on the hedera local node:
> 
> ```
>     ✔ iteration: 0; should be able to delete contract via Deletable#destroy() (5483ms)
>     ✔ iteration: 0; should be able to delete deletable2 and re-create it (12409ms)
>     ✔ iteration: 1; should be able to delete contract via Deletable#destroy() (4722ms)
>     ✔ iteration: 1; should be able to delete deletable2 and re-create it (11476ms)
> ```
> 
> Performance on the hardhat local node:
> 
> ```
>     ✔ iteration: 0; should be able to delete contract via Deletable#destroy() (844ms)
>     ✔ iteration: 0; should be able to delete deletable2 and re-create it (91ms)
>     ✔ iteration: 1; should be able to delete contract via Deletable#destroy() (42ms)
>     ✔ iteration: 1; should be able to delete deletable2 and re-create it (72ms)
> ```
> 
> As you can see on hardhat only the very first test case takes considerably longer than the other test cases and is 6.49x faster than the hedera local node, but in all of the subsequent test cases hardhat is anywhere from 112x to 160x faster. In the case of large contract deploys hardhat could be close to 3 orders of magnitude faster than the hedera local node.

Thanks @mshakeg these are the details we love to see so we can continue to improve your experiences.
As always appreciate the time and effort and we'll incorporate this into the upcoming improvements.
