### ISSUE TITLE
Local Node Docker Setup on Windows

### ISSUE THREAD

**Issue by Reccetech** [hashgraph/hedera-local-node#288]
### Description

In the instructions for docker setup of local node on Windows it specifies the following instruction:
dos2unix compose-network/mirror-node/init.sh

I do not believe "dos2unix" is a supported command in windows.

### Steps to reproduce

Open cmd on windows
Try to run command
message "'dos2unix' is not recognized as an internal or external command,
operable program or batch file."

### Hedera network

other

### Version

windows

### Operating system

Windows

**Comment by Nana-EC** [comment]
Thanks @Reccetech 

I think `dos2unix` is supported on Windows - https://dos2unix.sourceforge.io/
What might be happening here is that it doesn't have out of the box support on windows and our documentation doesn't say to install this command support.

We'll look into a resolution for this.

**Comment by Ivo-Yankov** [comment]
Hi @Reccetech,

Could you please specify your version of Windows? Also have you tried running the command in a WSL console?

**Comment by georgi-l95** [comment]
Hi @Reccetech , does this issue still persist ? If yes, can you answer above questions ?

**Comment by Reccetech** [comment]
This answers my question. I think we can close this issue. Thanks!
