### ISSUE TITLE
Increase starting balances for default accounts

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-local-node#291]
### Problem

The current starting balances for the default accounts (0.0.1002 through to 0.0.1031) is 10k HBAR, which equates to $1,200 based on the local node's native price of $0.12/HBAR. However, this balance is not sufficient for projects with large test suites, where the deployment of multiple contracts incurs significant fees that add up quickly.

To address this, I suggest increasing the starting balances of the default accounts to 10m HBAR each ($1.2m each). This increase will better support the development and testing of projects on the platform and prevent transactions from failing due to insufficient account balances.

### Solution

See above

### Alternatives

Alternatively, allow developers to configure the native price(including the gas price).

**Comment by Nana-EC** [comment]
Thanks @mshakeg 
Fair request.
Per your development practices what would be a sufficient  balance per account?

One idea might be we offer a configuration for startup that allows customization

**Comment by mshakeg** [comment]
@Nana-EC 10m HBAR($1.2m) is more than sufficient per account for my usage, but 1b HBAR per account(of the 30 accounts created) should be possible given a total of 50b HBAR is minted, and the more the merrier :)

**Comment by Nana-EC** [comment]
Whiles possible 10m does seem like quite a jump.
I'm open minded, it's just harder to go back down after increasing.
We want to make sure we support a multitude of test scenarios.

I think the best approach is a config for the default balance on accounts at start.

**Comment by georgi-l95** [comment]
This was addressed here :https://github.com/hashgraph/hedera-local-node/pull/297 . We can now specify how much HBAR balance we want at start, with `--balance` option.
