### ISSUE TITLE
Executing `npx hedera-local start` freezes at ` generating accounts

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [hashgraph/hedera-local-node#32]
### Description

Executing the following steps leads to freezing

### Steps to reproduce

1. npm install @hashgraph/hedera-local@1.0.1 -g
2. npx hedera-local start

The output the following:
<img width="352" alt="image" src="https://user-images.githubusercontent.com/12232750/167624602-c0948dc6-e7ef-4ea4-8879-847a80952bb0.png">

### Hedera network

other

### Version

v1.0.1

### Operating system

macOS

**Comment by Daniel-K-Ivanov** [comment]
Screenshots from the `hedera-node`:
![image](https://user-images.githubusercontent.com/12232750/173565158-5733620d-f79c-4bc2-aeac-abc754b61770.png)
![image](https://user-images.githubusercontent.com/12232750/173565192-2f9e2c94-4964-4317-8d15-4bd7dfad0be2.png)

**Comment by Kalina-Todorova** [comment]
Should be fixed with https://github.com/hashgraph/hedera-local-node/pull/121 
@Daniel-K-Ivanov could you verify this fixes the issue on your end?
