### ISSUE TITLE
JSON RPC rate limiting should be disabled for local node (running local network)

### ISSUE THREAD

**Issue by david-bakin-sl** [hashgraph/hedera-local-node#340]
### Problem

Annoying - not to mention useless - to have the hbar throttle when running the local node.

### Solution

Suggest defaulting `RELAY_RATE_LIMIT_DISABLED=true` in `.env`

**Comment by Nana-EC** [comment]
HBAR rate limiting should also be relaxed.
For now setting `HBAR_LIMIT_TOTAL_TINYBAR= 500_000_000_000` should be fine for high expense testing.
See https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/docs/hbar-limiting.md for more details
