### ISSUE TITLE
Environment variables for the mirror-node explorer should be updated

### ISSUE THREAD

**Issue by svienot** [hashgraph/hedera-local-node#393]
### Description

The environment variables for the explorer have all been recently renamed (as of release 23.7.0) because the toolchain used for VueJS build has been migrated from VueCLI to Vite. It also has to be noted that most explorer variables are only taken into account at build time. This is a VueJS limitation.

The only 2 variables which have an effect at runtime and need to be set by Local Node are those which allow to configure an additional network menu item pointing to the local mirror-node. These have been renamed as follows:
- `VUE_APP_LOCAL_MIRROR_NODE_MENU_NAME` is now `DOCKER_LOCAL_MIRROR_NODE_MENU_NAME`
- `VUE_APP_LOCAL_MIRROR_NODE_URL` is now `DOCKER_LOCAL_MIRROR_NODE_URL`

These 2 variables are treated specially by the Docker entrypoint which patches index.html to pass them as globals to the app.

The following variables have also been renamed but since they have no effect at runtime, they can be removed from Local Node configuration:
 - VUE_APP_PRODUCT_NAME
 - VUE_APP_DOCUMENT_TITLE_PREFIX
 - VUE_APP_ENABLE_STAKING

### Steps to reproduce

- hedera start --network local -d
- launch explorer at http://localhost:8080
- there is no LOCALNET menu item

### Hedera network

other

### Version

2.13.0

### Operating system

None

**Comment by svienot** [comment]
We would like to later replace this mechanism by a mount point allowing to provide a custom network configuration (including the local mirror-node). The impact on Local Node would be the inclusion of an additional JSON file and the definition of a volume in the `docker-compose.yml`, something like:
```
    volumes:
      - ./networks-config.json:/app/networks-config.json
```
Would that be adequate for Local Node?

**Comment by georgi-l95** [comment]
Yes, it is. Also thank you for reporting this bug.
