### ISSUE TITLE
Local node supported in Gitpod/Github Codespace/Jetbrains Space

### ISSUE THREAD

**Issue by david-bakin-sl** [hashgraph/hedera-local-node#400]
### Problem

How _quickly_ can I spin up a local node?

Especially: How quickly for a developer _new to Hedera_ who might just want to get toes in the water without even following a cookbook of pull this repo/start this docker container/ etc.

### Solution

Maybe local node could run in Gitpod/Github Codespaces/Jetbrains Space?  If so, there could be a `devcontainer.json` or `gitpod.yaml` or whatever to pull the right repos (including the sdks and examples) and docker images and get everything running.  Perhaps the browser IDE could be configured too (with appropriate plugins) if needed.

(Some additional work to make the developer experience really smooth might be desirable.)

**Comment by david-bakin-sl** [comment]
See also [this Slack thread](https://swirldslabs.slack.com/archives/C03DU0QGE2G/p1696436988915559?thread_ts=1696260074.597409&cid=C03DU0QGE2G) (in the Swirlds Labs internal Slack).

**Comment by georgi-l95** [comment]
@david-bakin-sl don't have access to this thread unfortunately

**Comment by david-bakin-sl** [comment]
Darn.  Exceptionally long thread.  Let me copy/paste a couple of highlights.

> David Bakin W.r.t. Matt's #4 and especially but not exclusively the "new developer" scenario, I wonder if local node is lightweight enough to run in Gitpod, Github Codespace, or Jetbrains Space?  These are cloud IDEs (usually VSCode that runs in a browser, except of course for Jetbrains) that spin up development machines in the cloud with decent compute resources (though short of disk, usually) that are pre-provisioned with whatever repos you want pulled, whatever docker containers you want running (that's all configurable).  Because it is easy to put a "run in gitpod" button on the local node repo (it already has a "create codespace button") and add the required configuration file ...
>
> These accounts typically have low monthly fees and usually have a free tier or a free allowance/month.  And they're quite nice to work with - spin-up speed is pretty fast though depends on how big a repo you're pulling or how big the docker images are. (edited)

> Ed Marquez @david.bakin  and team -
>
>I have looked into using GitPod for local node before. It kinda works.
>
> There are some issues with port naming, but I'm sure could be addressed. Here are my findings from a few months ago that I shared with Nana and others in DevRel:
![image](https://github.com/hashgraph/hedera-local-node/assets/117694041/1f939e80-2caf-4dc5-96fb-64a774d9b1cb): Documented the issues that I ran into initially - later figured out it was related to the names of ports (see img 3)
![image](https://github.com/hashgraph/hedera-local-node/assets/117694041/e6927081-b2ec-4dc4-a9c5-9da7904ba998): Local node running on GitPod using just a web browser. Console shows NFT creation, minting, burning, and transfer example runs successfully
![image](https://github.com/hashgraph/hedera-local-node/assets/117694041/e47e4adb-3be4-4070-866e-ea320a801308): Found out the port naming issue
![image](https://github.com/hashgraph/hedera-local-node/assets/117694041/3934c7a1-cc16-4258-acde-575d68791629): Referenced in Img3. Shows what the port names for different services look like (local Hashscan, JSON-RPC, mirror node, etc.)
> Again, just because "it works" today, it doesn't mean the solution is at a stage that would provide a smooth experience for devs. The feasibility is there, but additional work would be needed to make it as easy to use as possible. (edited)
