### ISSUE TITLE
Provide tooling and boilerplate for creating a localnode environment

### ISSUE THREAD

**Issue by pwoosam** [hashgraph/hedera-local-node#402]
### Problem

Using localnode can be difficult because it's time consuming to write scripts to generate your dapp's resources (tokens, contracts, topics, etc.) and configure your dapp to use the localnode environment.

### Solution

- Enhance CLI to provision resources on startup
- Add config file for defining custom scripts or resource definitions for execution/deployment on startup
- Generate config file (json/yaml/.env) for dapps to consume so they can easily use the new localnode environment and their generated resources
 
> NOTE: This could potentially be used for testnet to repopulate testnet after a reset as well

**Comment by rbair23** [comment]
I love this idea, and would also apply to FST (see discussion in #401).

**Comment by jaycoolslm** [comment]
This would definitely increase my chances of using local node for development

**Comment by georgi-l95** [comment]
Hey @pwoosam can you expand a little more on what's your use case (how do you connect your dapp to localnode, using sdk or relay), also what kind of scripts? For example you wanna be able to call a script which deploys contracts/token/etc.?

**Comment by georgi-l95** [comment]
Hey @jaycoolslm what's stoping you currently? Do you have anything in particular that you think we can improve ?

**Comment by jaycoolslm** [comment]
> Hey @jaycoolslm what's stoping you currently? Do you have anything in particular that you think we can improve ?

Lack of awareness and current ease if integrating public testnet eg. no prior set up, can just query endpoints immediately with endoints I know well

**Comment by pwoosam** [comment]
@georgi-l95 the dApps I have worked on have almost exclusively used the SDK. Although 1 dApp uses both the relay and SDK.

There are a series of common scripts used across projects:
- Create new NFT collection and mint X NFTs
- Create FT, create accounts, associate FT to accounts, distribute FTs to accounts
- Deploy contract(s) configuring the contract via the constructor and calling methods on the contract after deployment

Each of these scripts read the account id and private key for the SDK operator from environment variables (a .env file).
The scripts output the ids (and private keys) of the created resources to the console (stdout).

The ids of the created resources are then copy/pasted into a .env file for the dApp.


I imagine this is very similar to what most dApp developers in the Hedera space are doing.

**Comment by Nana-EC** [comment]
We could reuse the [MN Monitor](https://github.com/hashgraph/hedera-mirror-node/tree/main/docs/monitor#publish) logic for env setup.
This flow is already used extensively for testing and setup of perf and test environment every release.

**Comment by georgi-l95** [comment]
Hey @pwoosam we are going to soon priorities and work on this, apart from the ones you've mention in your comment [here](https://github.com/hashgraph/hedera-local-node/issues/402#issuecomment-1757991471), can you think of any more cases or examples that we can add ?
