### ISSUE TITLE
Cannot start when redis-server port is busy

### ISSUE THREAD

**Issue by Ivo-Yankov** [hashgraph/hedera-local-node#411]
### Problem

The local node hangs when trying to start with an already busy 6379 port. The following error is spammed in the output:
```
Error: connect ECONNREFUSED 127.0.0.1:5600
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5600
}
Waiting for the containers at 127.0.0.1:5600, retrying in 0.1 seconds...
```

6379 is the default port of `redis-server` and a lot of systems start that service on startup.

### Solution

One way to solve this is to use a different port for the redis container. Another would be to provide a more descriptive error message.

**Comment by stefan-stefanooov** [comment]
Issue has been fixed this [MR](https://github.com/hashgraph/hedera-local-node/pull/479)
