### ISSUE TITLE
Token info takes longer to display changes after update

### ISSUE THREAD

**Issue by yiliev0** [hashgraph/hedera-local-node#416]
### Description

Executing a token update transaction(changing symbol) the explorer takes a while until the token update is shown. This is not reproducible on previewnet, so it means it's an isolated issue for the local node. On previewnet it usually takes around 2s and for local node it is around 20-30s.

### Steps to reproduce

1. Create a token
2. Find the token in the explorer
3. Execute update transaction for changing the symbol

**Expected result**: After 2s the new symbol should be visible
**Actual result**: It takes somewhere around 20s-30s so the changes are visible.(longer than expected)

### Hedera network

other

### Version

2.15.1

### Operating system

None

**Comment by natanasow** [comment]
Executed the described flow against testnet/previewnet/local-node and it's not reproducible anymore. The updated token information is displayed in explorer's dashboard as soon as the contract result is imported into the mirror node's database (timeframe of 2 seconds). I confirmed it with @yiliev0 (issue owner) and the issue may be marked as resolved IMO (cc @Nana-EC).

**Comment by natanasow** [comment]
Not reproducible anymore.
