### ISSUE TITLE
Add Hedera Mirror Node Explorer to the local node

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-local-node#42]
### Problem

It is difficult to see what happened on my network when I ran transactions. I can query the mirror node, but that is pretty low level.

### Solution

Add the mirror node explorer to the set of containers. It should be wired up to the mirror node by default.

**Comment by Kalina-Todorova** [comment]
This was added in https://github.com/hashgraph/hedera-local-node/releases/tag/v.2.0.0
