### ISSUE TITLE
Support hardhat and foundry console.log

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-local-node#421]
### Problem

When iteratively developing smart contracts against a local node, the console.log from frameworks like hardhat and foundry are very useful and time savers.  The alternative is to define DEBUG events, and emit them in the smart contracts and then read them in the driving javascript or typescript code.   The console.log requires one import into the contract being developed and the it can be used to log values in the local node running.

### Solution

- support the hardhat console.log, "import "hardhat/console.sol";
- support the foundry console.log "import "forge-std/console.sol";

### Alternatives

Emitting debug events as described above.

**Comment by georgi-l95** [comment]
This is work most likely in the smart-contract repo/relay or on a deeper level. You can see [this](https://github.com/hashgraph/hedera-smart-contracts/issues/675#issuecomment-2244717029) comment. Closing this as there is nothing we can do here. Feel free to open, if you know a way with which we can enable this in local-node.
