### ISSUE TITLE
Add FAQ Section

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-local-node#438]
### Solution

Add FAQ section in the [README.md](https://github.com/hashgraph/hedera-local-node/blob/main/README.md) for users to reference when problem occurs.

**Comment by georgi-l95** [comment]
Windows Frequent problems:
> Postgres error: 
> ` /usr/local/bin/docker-entrypoint.sh: /docker-entrypoint-initdb.d/init.sh: /bin/bash^M: bad interpreter: No such file or directory
> `
> Solution:
> ```Configure Git not to convert line endings on checkout by running
> git config --global core.autocrlf input
> Delete your local repository.
> Clone it again.
> ```

**Comment by Nana-EC** [comment]
@natanasow for consideration in upcoming sprint
