### ISSUE TITLE
Unable to Start Node

### ISSUE THREAD

**Issue by NehaSunkum** [hashgraph/hedera-local-node#446]
Hi I was trying to start the Hedera Local node based on the instructions in the README doc in the repo. I am running into the issue below.

Step 1: git clone https://github.com/hashgraph/hedera-local-node.git
Step 2: cd hedera-local-node
Step 3: docker compose up -d

Error: 
Error response from daemon: driver failed programming external connectivity on endpoint relay-cache (04cbc92e2eda667894787a8f7ae6f7f2bb2ba9703eb04761881b4466493a028e): Error starting userland proxy: listen tcp4 0.0.0.0:6379: bind: address already in use

Error Screenshot is also attached
![HederaLocalNodeError](https://github.com/hashgraph/hedera-local-node/assets/8645790/d0e9aaff-0de8-4f8d-ac34-64a43a50a1e4)

**Comment by georgi-l95** [comment]
It seems that one of the ports that are used in the hedera-local-node is already taken on your machine. Can you free it up or change the port in the docker-compose file in the root directory.
Also strongly recommend starting using `npm run start -- -d` for example, as this not only brings the containers up, but creates initial accounts, import fees and performs several checks to make sure that the node is up and running.

**Comment by NehaSunkum** [comment]
is npm a replacement for the docker steps or does it need to be run in addition to the docker steps?

**Comment by georgi-l95** [comment]
It's a replacement. Also docker steps are possible, just keep in mind that it may be unstable and will not have any accounts, only the treasury. But the issue here is that the port is already used by something else, so resolving this should allow you to start with either npm or docker step.

**Comment by NehaSunkum** [comment]
okay thank you and is it possible to do this setup without this step listed in the documentation?
![image](https://github.com/hashgraph/hedera-local-node/assets/8645790/1073cef9-2d36-486a-be2b-f50ae03bdeb8)

**Comment by georgi-l95** [comment]
This is already done, when you start the local node with npm or docker steps. You will have this treasury either way. If you start using npm, you will have 30 additional accounts with 2 types of keys.

**Comment by NehaSunkum** [comment]
Okay but we still have to pay the fees associated with each transaction right?

**Comment by georgi-l95** [comment]
Yes, each transaction should be payed.

**Comment by Palak3196** [comment]
Hi Georgi,

I'm Neha's colleague. I'd like to add here if its not an issue.

So even if we don't participate in the transactions, do we still have to pay to have the local node up? if we just want to query the transaction data of a block/of an address?

**Comment by georgi-l95** [comment]
No, you don't need to pay anything for local node to be up. You can query this data free from the mirror node using the appropriate endpoints.

**Comment by georgi-l95** [comment]
I think you can use transaction endpoint and specify the timestamp for the blocks you want. For example, here are the transactions between the start timestamp of this block and end of this block, so basically all transactions in the block
https://mainnet-public.mirrornode.hedera.com/api/v1/transactions?limit=100&order=asc&timestamp=gt%3A1569041250.290137000&timestamp=lt%3A1569041254.980005000&transactiontype=cryptotransfer

**Comment by georgi-l95** [comment]
Closing this issue, as it's not an issue. If you need more help, we can turn it in disscussion
