### ISSUE TITLE
DEV_MODE needs to be set to `true` in the local node.

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-local-node#456]
### Description

Currently the local node is meant for iterative development and CI, and DEV_MODE is set to `false`.  DEV_MODE needs to be set to `true` in order for contract revert reasons to be returned to the test app. 

### Steps to reproduce

1. The current .env file has `RELAY_DEV_MODE` set to `false`
2. Once the local node is started you can get into the container and verify that `DEV_MODE` is set to `false`.
`docker exec -it <container ID> /bin/bash`
`env`
```
REDIS_URL=redis://127.0.0.1:6379
HOSTNAME=0c651e8c172a
LOCAL_NODE=true
FEE_HISTORY_MAX_RESULTS=10
DEV_MODE=false
YARN_VERSION=1.22.19
OPERATOR_ID_MAIN=0.0.2...
```

### Hedera network

other

### Version

v2.16.0

### Operating system

macOS

**Comment by georgi-l95** [comment]
Hey @ebadiere is this still valid ? What was decided here ?

**Comment by ebadiere** [comment]
N/A. We don't key off of DEV_MODE to provide contract revert messages.
