### ISSUE TITLE
Haveged container errors and restarts continuously

### ISSUE THREAD

**Issue by tuddman** [hashgraph/hedera-local-node#482]
### Description

Haveged container fails to run properly.

[gcr.io/hedera-registry/network-node-haveged:0.43.4](https://github.com/hashgraph/hedera-local-node/issues/new?assignees=&labels=bug&projects=&template=bug.yml#)

a42af335cb0a45121cec6946c39af2f3d2c72d51a6166c8686e220228df60b54

Haveged container logs:

```
...
2023-12-30 05:10:04 haveged starting up
2023-12-30 05:10:57 haveged starting up
2023-12-30 05:11:59 haveged starting up
2023-12-30 05:08:59 haveged: Couldn't initialize HAVEGE rng 9
2023-12-30 05:09:01 haveged: Couldn't initialize HAVEGE rng 9
...
```

### Steps to reproduce

1. clone this repo
2. `docker compose up -d`
 
The other containers in the `docker-compose.yml` file appear to start and operate normally.
But this faulty container is preventing all further progress in using `hedera-local-node`.

The Hedera network listed below is: `Other` => "local"

### Additional context

<img width="1114" alt="Screen Shot 2023-12-30 at 5 18 53 AM" src="https://github.com/hashgraph/hedera-local-node/assets/33383/537d3982-4b0a-439c-a047-1f9bc807a93f">

### Hedera network

other

### Version

0.43.4

### Operating system

macOS

**Comment by georgi-l95** [comment]
Hey @tuddman we are aware of this issue, however it should not stop the network from working properly. You should still have a fully working network, because this container is not used. Can you try some operations and report back with some error, if it's not working.
