### ISSUE TITLE
Stopped docker unneeded resource check.

### ISSUE THREAD

**Issue by stefan-stefanooov** [hashgraph/hedera-local-node#505]
### Description

When docker is stopped, the local node does unnecessary check.

> [Hedera-Local-Node] ERROR (DockerService) Docker is not running.
> [Hedera-Local-Node] ERROR (DockerService) Your docker memory resources are set to 0.00GB. This is not enough, set to at least 4GB

Please investigate and remove this check if necessary 

### Steps to reproduce

Stop docker.
Try to run local node

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by georgi-l95** [comment]
This is not anymore a problem, fixed or requirments changed.
