### ISSUE TITLE
Updating dependencies breaks account creation

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-local-node#640]
### Description

Bumping dependencies like sdk, breaks the local-node account creation.

### Steps to reproduce

1. Run npm i
2. Start local-node

### Hedera network

mainnet, testnet, previewnet, other

### Version

main

### Operating system

None

**Comment by konstantinabl** [comment]
This issue is caused by changes of AccountInfoQuery in the sdk, which are now being reverted, so the issue will be fixed
Reference ->  https://github.com/hashgraph/hedera-sdk-js/pull/2328
