### ISSUE TITLE
SDK actions workflow is failing at starting local node

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-local-node#641]
### Description

In the SDK actions workflow, starting the local node is taking longer then expected and then cancels.  I am trying to re run the actions and it is at the start local node step for almost 10 mins where before it finished in about 3 mins. This is blocking merging our PRs and releases. 

What is the normal start up time for local node? 
![Screenshot 2024-06-10 at 4 56 20 PM](https://github.com/hashgraph/hedera-local-node/assets/21989138/eb2ed41c-6ed2-47cd-b838-98eb0077fdc7)

### Steps to reproduce

You can view the workflow here: https://github.com/hashgraph/hedera-sdk-java/actions/runs/9444345973/job/26050353131

### Hedera network

other

### Version

latest 

### Operating system

None

**Comment by SimiHunjan** [comment]
also do we need to tag 0.51.1 for local node for it to include the changes we made to token relationships on consensus nodes? 

You can see another example for the cancel at the step of starting local node here: https://github.com/hashgraph/hedera-sdk-java/actions/runs/9446934873/job/26029147046?pr=1842

**Comment by SimiHunjan** [comment]
Example of previous job completing successfully https://github.com/hashgraph/hedera-sdk-java/actions/runs/9398275418/job/25883410390

**Comment by SimiHunjan** [comment]
not sure if the is the same or related issue to what I have described: https://github.com/hashgraph/hedera-local-node/issues/640

**Comment by georgi-l95** [comment]
This is due to bug in the SDK, this issue will resolve it -> https://github.com/hashgraph/hedera-sdk-js/pull/2328

**Comment by georgi-l95** [comment]
Fixed.
