### ISSUE TITLE
Connection refused for Mirror Node GRPC Endpoint

### ISSUE THREAD

**Issue by walter-hernandez** [hashgraph/hedera-local-node#76]
### Description

Hello all,

Trying to start the local node with the following command:
`npx hedera-local start`

I had the following error:

<img width="618" alt="image" src="https://user-images.githubusercontent.com/52283659/173246182-3f7dd67b-c333-4628-a520-66811e0c73fc.png">

It looks like the Mirror Node GRPC Endpoint refusing a connection to the port **5600** when using the package hedera-local. 

I tried standing the network using `docker-compose up -d`. So, I checked that all the docker containers were running and listening with the right ports:
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/52283659/173246222-6b940356-ef5e-4085-be99-26f9d5b774fd.png">

It seems to have worked

### Steps to reproduce

1. Clone repo
2. Execute `docker-compose up -d`
3. Run `npx hedera-local start` to get the defaults accounts

### Additional context

<img width="618" alt="image" src="https://user-images.githubusercontent.com/52283659/173246182-3f7dd67b-c333-4628-a520-66811e0c73fc.png">

### Hedera network

other

### Version

v1.0.1

### Operating system

macOS

**Comment by nathanklick** [comment]
@walter-hernandez Good afternoon! Looking at the above screenshots it appears you are running an older version of the container images. 

Would you mind pulling the latest commits from the `main` branch and retrying the `npx hedera-local start` command? 

We updated the container images about 3 weeks ago  and on Friday June 10th.

**Comment by nathanklick** [comment]
@walter-hernandez I wanted to follow up and see if the latest commits from the `main` branch has resolved your issues. Please let us know if you are still having issues or if we can close this ticket. Thanks!

**Comment by walter-hernandez** [comment]
Hello @nathanklick. I tried it with the latest commit and doing `npx hedera-local start` I got this error:

<img width="691" alt="image" src="https://user-images.githubusercontent.com/52283659/175834385-9346df1d-0e7c-43b2-8853-0922ee13ada9.png">



 I got a different error when I stopped all the containers and run: `npx hedera-local start` 

<img width="635" alt="image" src="https://user-images.githubusercontent.com/52283659/175833841-c718363a-e97f-44db-a439-99c7a5ed0d22.png">

These are the containers:

**Comment by walter-hernandez** [comment]
Hello @Kalina-Todorova! I confirmed that now it is working:

This is testing with a simple transaction from the example in https://docs.hedera.com/guides/docs/sdks/set-up-your-local-network :

<img width="760" alt="image" src="https://user-images.githubusercontent.com/52283659/181996377-f23633ae-7bdb-4290-b439-706ae7afcbd7.png">

Thank you for solving the issue! I am going to close this issue as solved
