### ISSUE TITLE
Docker Local Node stops working with PLATFORM_NOT_ACTIVE error after a while

### ISSUE THREAD

**Issue by jaycoolslm** [hashgraph/hedera-local-node#800]
### Description

I am running the local node on my Mac Studio. Set up with 

`npm install @hashgraph/hedera-local -g`
then 
`hedera start`

Docker specs are set as requested.

Localnode works fine for a while, then it seems to time out. Last log in network-node container is:

`Hedera - HederaNode#0 is CHECKING`

As you can see, early it goes CHECKING -> ACTIVE

![Screenshot 2024-10-20 at 12 20 37](https://github.com/user-attachments/assets/0b2df9c5-045c-49ac-8993-707b2d1527a8)

The error I now get run trying to create tokens is:

Error: max attempts of 10 was reached for request with last error being: PLATFORM_NOT_ACTIVE

### Steps to reproduce

Run local node for a while, then stop, then try again (sorry... not very specific)

### Hedera network

other

### Version

2.31.0

### Operating system

macOS

**Comment by jaycoolslm** [comment]
Something else (minor I think)

I just got this error:

```
Error on xterm-256color.Setulc:
"\u001b[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m"

var v,
 stack = [],
 out = ["\x1b[58::2::"];
(stack.push(v = params[0]),
 v),
(stack.push(v = 65536),
 v),
(v = stack.pop(),
 stack.push(v = (stack.pop() / v) || 0),
 v),
out.push(stack.pop()),
out.push("::"),
(stack.push(v = params[0]),
 v),
(stack.push(v = 256),
 v),
(v = stack.pop(),
 stack.push(v = (stack.pop() / v) || 0),
 v),
(stack.push(v = 255),
 v),
(v = stack.pop(),
 stack.push(v = (stack.pop() & v) || 0),
 v),
out.push(stack.pop()),
out.push("::"),
(stack.push(v = params[0]),
 v),
(stack.push(v = 255),
 v),
(v = stack.pop(),
 stack.push(v = (stack.pop() & v) || 0),
 v),
out.push(stack.pop())}out.push("m");
return out.join("");
```

when running `hedera restart`

**Comment by corrosive4354** [comment]
Make sure that Docker's resource configuration (such as CPU and memory) is sufficient to prevent the node from stopping responding due to insufficient resources.
If it still doesn't work, you can try using [Servbay](https://servbay.com) instead of docker, which is better than docker on mac and has fewer bugs

**Comment by jaycoolslm** [comment]
Okay, CPU and memory is set up to the levels suggested in the docs. CPU is actually way higher than whats recommended. What would you recommend increasing memory to? +20%?

`hedera restart` command always seems to fix it at least

**Comment by jaycoolslm** [comment]
@natanasow  seems better now
