### ISSUE TITLE
Docker resources check fails on Windows Server 2022

### ISSUE THREAD

**Issue by mishomihov00** [hashgraph/hedera-local-node#806]
### Description

When trying to start the hedera local node with "npx hedera start --verbose=trace --detached --network-tag=0.54.0-alpha.5" the workflow fails on checking the docker resources - https://github.com/hashgraph/hedera-sdk-cpp/actions/runs/11497843949/job/32002391904?pr=803#step:7:25

I think that the problem is related to the JSON format output and the following checks for the MemTotal and NCPU, as this output seems to be a bit different on different operating systems - https://github.com/hashgraph/hedera-local-node/blob/main/src/services/DockerService.ts#L206

This is happening with both 2.29.2 version and the latest one.

### Steps to reproduce

Run `npx hedera start --verbose=trace --detached --network-tag=0.54.0-alpha.5` on a Windows Server.

### Version

2.29.2

### Operating system

Windows

**Comment by Ivo-Yankov** [comment]
I managed to fix the immediate error described here, but the local-node is not starting in a windows-2022 CI. I will investigate it further and get back to you.

**Comment by Ivo-Yankov** [comment]
The issue is fixed and the local-node can now run on Windows, but it requires WSL v2. Unfortunatelly that is not supported in the github runners and we are unable to automate the tests on Windows. I described the problem in this [issue](https://github.com/hashgraph/hedera-local-node/issues/817)
