### ISSUE TITLE
Mounts denied error on docker compose up

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-local-node#819]
### Description

Running a `docker compose up -d` in a new setup resulted in a 

```
Error response from daemon: Mounts denied:
The path .../hedera-local-node/envoy.yaml is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/settings/mac/#file-sharing for more info.
```

This step isn't documented anywhere and if possible shouldn't be required

### Steps to reproduce

1. git clone https://github.com/hashgraph/hedera-local-node.git
2. cd hedera-local-node
3. npm install
4. docker compose up -d

### Additional context

Adding the project directory to the "Virtual file shares" list under Docker settings -> Resources -> File sharing, did fix the issue, but it's an additional hurdle to easy usage of local node

### Hedera network

other

### Version

v2.31.0

### Operating system

None

**Comment by natanasow** [comment]
Action plan:
- adding a big section in the README.md pointing out `Docker settings -> Resources -> File sharing` setting
- adding debug trace log in case of error

This might resolve #818 as well.

**Comment by isavov** [comment]
@natanasow @Nana-EC
It's worth noting where the repository is being cloned to. Be default certain directories are already shared in Docker, and should work out of the box.
<img width="786" alt="Screenshot 2024-10-31 at 15 39 33" src="https://github.com/user-attachments/assets/6dece5fb-6008-42b6-90d5-dd01fa610b4b">
If running from a common location like a user's Desktop or Documents directory (or a sub-directory of it) it's common to get a one time popup from docker asking for access to it, like so:
<img width="280" alt="Screenshot 2024-10-31 at 15 48 23" src="https://github.com/user-attachments/assets/15969161-c6c1-4446-b1f4-0153219173e2">
If cloning to a sub-directory in one of the default shared directories it should work without further adjustments (just tested on a Macbook that never had hedera-local-node installed to it before).
