### ISSUE TITLE
Unable to bring up local node

### ISSUE THREAD

**Issue by lukelee-sl** [hashgraph/hedera-local-node#822]
### Description

I was unable to start local node against a pull of the latest main branch.

### Steps to reproduce

- Pulled the latest
- tried to run `nom run start --d` which failed.
- tried `docker compose up` and failed to load and received the following response
```
[+] Running 8/8
 ✘ monitor Error      context canceled                                                                 0.8s 
 ✘ grpc Error         context canceled                                                                 0.8s 
 ✘ relay-ws Error     context canceled                                                                 0.8s 
 ✘ rest Error         context canceled                                                                 0.8s 
 ✘ importer Error     context canceled                                                                 0.8s 
 ✘ network-node Error context canceled                                                                 0.8s 
 ✘ relay Error        Head "https://ghcr.io/v2/hashgraph/hedera-json-rpc-relay/manifes...              0.8s 
 ✘ web3 Error         context canceled                                                                 0.8s 
Error response from daemon: Head "https://ghcr.io/v2/hashgraph/hedera-json-rpc-relay/manifests/0.56.0": denied: denied
```

### Hedera network

other

### Version

latest main

### Operating system

macOS

**Comment by david-bakin-sl** [comment]
FYI I get an "UNAUTHORIZED" on hitting that url from the browser, also for other release manifests in that repo.  Artifact repository permissions issue?

**Comment by natanasow** [comment]
Locally docker logging out from the gcr resolved the issue
```
docker logout gcr.io
```

Also, make sure there are no already defined env variables that override with these in the hedera-local-node .env file.
