### ISSUE TITLE
Add Info message after npm install

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [hashgraph/hedera-local-node#83]
There is an `postinstall` script executed after the `npm install` script.
It executes the `docker-compose build` command in order to download and prepare the consensus and mirror node images.

The problem is that users do not expect that they must run docker compose when they do `npm install`. 

**Solution**
Add info message saying that docker must be running in order to finish the `npm install` script. 
Currently the user sees only:

<img width="925" alt="image" src="https://user-images.githubusercontent.com/12232750/173561050-6ac57f9e-8948-4a80-a39e-b8668b59bcc9.png">

**Comment by Kalina-Todorova** [comment]
https://docs.npmjs.com/cli/v8/using-npm/scripts

**Comment by Kalina-Todorova** [comment]
Not needed anymore.
