### ISSUE TITLE
CLI Should keep the process on focus and not in the background

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [hashgraph/hedera-local-node#84]
Currently when `npx local-node start` is executed there are a bunch of scripts that are performed and after that the node is running in the background. This is flawed because developers do not know what / whether something is running and may even "forget" that they are running a local node.

**Solution**
When the local node is started, keep the process on focus and not place it in the background. Executing CMD + C or CTRL + C should stop the process

**Comment by Kalina-Todorova** [comment]
Blocked by: https://github.com/hashgraph/hedera-services/issues/3749
