### ISSUE TITLE
Local node needs a pinger for reliable mirror operation

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-local-node#90]
### Description

The creation of record files every 2s is entirely dependent on a steady stream of transactions, if the local node is operating with low throughput, transactions can fail to appear in mirror node until another transaction is submitted.

Suggest we implement  "pinger" which executes a crypto transfer from 0.0.2 to 0.0.3 (for example) such that there is a constant stream of transactions, maybe execute the transaction every second or every 2 seconds.

### Steps to reproduce

Start a local network, execute a single transaction, check mirror node, the transaction doesn't appear until another transaction is sent to the network some time later.

### Hedera network

other

### Version

v1.0.2

**Comment by Neurone** [comment]
It seems a pinger is already present (https://github.com/hashgraph/hedera-local-node/blob/main/src/pinger.js).
I tested with `npx hedera-local start` (https://github.com/hashgraph/hedera-local-node#npx-hedera-local-start-options), and it seems to serve the purpose to keep the mirror up-to-date.

I noticed a huge delay in the creation of the balance file, maybe for development purpose it can be useful to set it with more frequent updates.
