### ISSUE TITLE
Newest docker images(0.26.2) not working on Apple M1

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-local-node#91]
**Description**
Creating EVM account with `HederaSDK.TransferTransaction` against `hedera-local-node` gives the following error:

![local-node-2](https://user-images.githubusercontent.com/47981732/174040378-f51dcfb3-0a99-4a60-8279-01adb8e646be.png)
The transaction is executed successfully but the error comes when it tries to get the tx receipt.
(script causes the error is shown below)

**Hedera Local Node**
All docker services are up and running, also I am able to generate accounts successfully

![local-node-1](https://user-images.githubusercontent.com/47981732/174040964-2bfad48a-844d-4d87-aa18-e9762b515558.png)

**NodeJs Script for creating EVM account**
```
async function createAccountFromCompressedPublicKey() {
    const HederaSDK = require('@hashgraph/sdk');
    const ethers = require('ethers');
    const client = HederaSDK.Client
        .forNetwork({
            '127.0.0.1:50211': '0.0.3'
        })
        .setOperator('0.0.2', '302e020100300506032b65700422042091132178e72057a1d7528025956fe39b0b847f200ab59b2fdd367017f3087137');

    const wallet = ethers.Wallet.createRandom();
    const compressedPublicKey = wallet._signingKey().compressedPublicKey.substring(2);
    // console.log('private key', wallet.privateKey);
    // console.log('public key', compressedPublicKey);

    const nodeId = [HederaSDK.AccountId.fromString('0.0.3')];
    const publicKey = HederaSDK.PublicKey.fromString(compressedPublicKey).toAccountId(0, 0);

    const transferTransaction = new HederaSDK.TransferTransaction()
        .addHbarTransfer(client.operatorAccountId, new HederaSDK.Hbar(-1000))
        .addHbarTransfer(publicKey, new HederaSDK.Hbar(1000))
        .setNodeAccountIds(nodeId);
    const tx = await transferTransaction.execute(client);
    console.log('tx: ',tx.toString())
    const receipt = await tx.getReceipt(client);
    console.log('receipt: ', receipt.status.toString());
}
```

uses "@hashgraph/sdk": "2.15.0"
**The script above is working fine on Ubuntu machine.**

Once the error `"max attempts of 10 was reached for request with last error being: UNKNOWN"` is received, the local-node becomes unusable. The command `npx hedera-local generate-accounts 2` freezes.

![local-node-3](https://user-images.githubusercontent.com/47981732/174042984-beef4117-08d4-4f5f-8a70-2c08f040b493.png)

There is no suspicious logs on any docker service.

*Haveged*(v. 0.26.2)

![local-node-5](https://user-images.githubusercontent.com/47981732/174044533-cc1eeb93-d867-49db-b434-97d2416141cb.png)

*Network-node*(v. 0.26.2)

![local-node-4](https://user-images.githubusercontent.com/47981732/174044581-d9b5a562-3227-4460-b30d-ebf08d315c50.png)

**System specs**
MacBook Pro
Chip - Apple M1 Pro

**Comment by ar-conmit** [comment]
I was able to create an EVM account with the same script from above using older docker images introduced in the PR[#47](https://github.com/hashgraph/hedera-local-node/pull/47):
`NETWORK_NODE_IMAGE_TAG=0.25.3`
`HAVEGED_IMAGE_TAG=0.25.3`


![local-node-6](https://user-images.githubusercontent.com/47981732/174066999-96798da8-6741-405b-8649-2e1c358d5e81.png)

**Comment by nathanklick** [comment]
As discussed, the solution requires an updated `besu-native` library with Linux arm64 support. Issue hashgraph/hedera-services#3546 has been opened to track the delivery of an updated `besu-native` library.
